WEB/Areas/Education/Models/ViewModels/Students/CreateStudentVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace WEB.Areas.Education.Models.ViewModels.Students
{
    public class CreateStudentVM
    {
        [Display(Name = "Ad")]
        public string? FirstName { get; set; }

        [Display(Name = "Soyad")]
        public string LastName { get; set; }

        [Display(Name = "E-Mail")]
        public string Email { get; set; }
        
        [Display(Name = "Doğum Tarihi")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Kurs")]
        public Guid? CourseId { get; set; }
        
        [Display(Name = "Eğitmen")]
        public Guid? TeacherId { get; set; }

        [Display(Name = "Sınıf")]
        public Guid? ClassroomId { get; set; }
      
        public string? ImagePath { get; set; }
        
        [Display(Name = "Resim")]
        public IFormFile? Image { get; set; }

        public SelectList? Courses { get; set; }

        [Display(Name = "Kayıt Ücreti")]
        public double? RegisterPrice { get; set; }
    }
}

WEB/Areas/Education/Models/ViewModels/Students/GetStudentVM.cs
using ApplicationCore.Consts;
using System.ComponentModel.DataAnnotations;

namespace WEB.Areas.Education.Models.ViewModels.Students
{
    public class GetStudentVM
    {
        public Guid Id { get; set; }
        public string FullName { get; set; }
        public string BirthDate { get; set; }
        public string Email { get; set; }
        public string CourseName { get; set; }
        public string ClassroomName { get; set; }
        public string TeacherName { get; set; }
        public string? RegisterPrice { get; set; }
        public double? Average { get; set; }
        public string Status { get; set; }
        public string StudentStatus { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}

WEB/Areas/Education/Models/ViewModels/Students/StudentDetailForProjectVM.cs
using ApplicationCore.Consts;
using ApplicationCore.Entities.Concrete;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WEB.Areas.Education.Models.ViewModels.Students
{
    public class StudentDetailForProjectVM
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string ClassroomName { get; set; }
        public string CourseName { get; set; }
        public double? Exam1 { get; set; }
        public double? Exam2 { get; set; }
        public double? ProjectExam { get; set; }
        public double? Average { get; set; }
        public StudentStatus StudentStatus { get; set; }
        public string? ProjectName { get; set; }
        public string? ProjectPath { get; set; }
        public string? ImagePath { get; set; }
        public IFormFile? Project { get; set; }
        public Guid ClassroomId { get; set; }

    }
}

WEB/Areas/Education/Models/ViewModels/Students/UpdateStudentVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace WEB.Areas.Education.Models.ViewModels.Students
{
    public class UpdateStudentVM
    {
        public Guid Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        [Display(Name = "Ad")]
        public string? FirstName { get; set; }

        [Display(Name = "Soyad")]
        public string LastName { get; set; }

        [Display(Name = "E-Mail")]
        public string Email { get; set; }

        [Display(Name = "Doğum Tarihi")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Sınıf")]
        public Guid? ClassroomId { get; set; }

        [Display(Name = "Kurs")]
        public Guid? CourseId { get; set; }

        [Display(Name = "Eğitmen")]
        public Guid? TeacherId { get; set; }

        public string? ImagePath { get; set; }

        [Display(Name = "Resim")]
        public IFormFile? Image { get; set; }

        [Display(Name = "Kayıt Ücreti")]
        public double? RegisterPrice { get; set; }

        public SelectList? Courses { get; set; }
        public SelectList? Classrooms { get; set; }
        public SelectList? Teachers { get; set; }
    }
}

WEB/Areas/Education/Controllers/ClassroomsController.cs
using ApplicationCore.Consts;
using ApplicationCore.Entities.Concrete;
using AutoMapper;
using Business.Manager.Interface;
using DTO.Concrete.ClassroomDTO;
using DTO.Concrete.CourseDTO;
using DTO.Concrete.TeacherDTO;
using DTO.Concrete.UserDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WEB.Areas.Education.Models.ViewModels.Classrooms;
using WEB.Areas.Education.Models.ViewModels.Courses;
using WEB.Areas.Education.Models.ViewModels.Students;
using WEB.Areas.Education.Models.ViewModels.Teachers;

namespace WEB.Areas.Education.Controllers
{
    [Area("Education")]
    
    public class ClassroomsController : Controller
    {
        private readonly IClassroomManager _classroomManager;
        private readonly IMapper _mapper;
        private readonly ITeacherManager _teacherManager;
        private readonly ICourseManager _courseManager;
        private readonly IStudentManager _studentManager;
        private readonly IUserManager _userManager;

        public ClassroomsController(IClassroomManager classroomManager, IMapper mapper, ITeacherManager teacherManager, ICourseManager courseManager, IStudentManager studentManager, IUserManager userManager)
        {
            _classroomManager = classroomManager;
            _mapper = mapper;
            _teacherManager = teacherManager;
            _courseManager = courseManager;
            _studentManager = studentManager;
            _userManager = userManager;
        }
        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> Index()
{
    var classrooms = await _classroomManager.GetFilteredListAsync
        (
            select: static x => new GetClassroomVM
            {
                Id = x.Id,
                Name = x.Name,
                CourseName = x.Teacher.Course.Name,
                Description = x.Description,
                
                TeacherName = x.Teacher.FirstName + " " + x.Teacher.LastName,
                ClassroomSize = x.Students.Where(x => x.Status != Status.Passive).ToList().Count,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate != null ? x.UpdatedDate.Value.ToString("d.M.yyyy HH:mm:ss") : " - ",
                Status = x.Status == Status.Active ? "Aktif" : "Güncellenmiş"
            },
            where: x => x.Status != Status.Passive,
            orderBy: x => x.OrderByDescending(z => z.CreatedDate),
            join: x => x.Include(z => z.Teacher).ThenInclude(t => t.Course).Include(z => z.Students)
        );

    return View(classrooms);
}


        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> CreateClassroom()
        {
            var model = new CreateClassroomVM
            {
                Courses = await GetCourses()
            };
            return View(model);
        }

        [Authorize(Roles = "admin, customerManager")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateClassroom(CreateClassroomVM model)
        {
            model.Courses = await GetCourses();

            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<CreateClassroomDTO>(model);
                var result = await _classroomManager.AddAsync(dto);

                if (result)
                {
                    TempData["Success"] = $"{dto.Name} sınıfı sisteme kaydedilmiştir!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Sınıf sisteme kaydedilememiştir!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> UpdateClassroom(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Sınıf bulunamamıştır!";
                return RedirectToAction(nameof(Index));
            }
            var classroomDto = await _classroomManager.GetByIdAsync<UpdateClassroomDTO>(entityId);
            if (classroomDto != null)
            {
                var model = _mapper.Map<UpdateClassroomVM>(classroomDto);
                var courseId = await _courseManager.GetCourseIdByClassroomIdAsync(entityId);
                model.Courses = await GetCourses(courseId);
                model.Teachers = await GetTeachers(model.TeacherId);
                model.CourseId = courseId;
                return View(model);
            }
            TempData["Error"] = "Sınıf bulunamamıştır!";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin, customerManager")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateClassroom(UpdateClassroomVM model)
        {
            var courseId = await _courseManager.GetCourseIdByClassroomIdAsync(model.Id);
            model.Courses = await GetCourses(courseId);
            model.Teachers = await GetTeachers(model.TeacherId);
            model.CourseId = courseId;

            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<UpdateClassroomDTO>(model);
                var result = await _classroomManager.UpdateAsync(dto);
                if (result)
                {
                    TempData["Success"] = "Sınıf güncellenmiştir!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Sınıf güncellenememiştir!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);

        }

        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> DeleteClassroom(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Sınıf bulunamamıştır!";
                return RedirectToAction(nameof(Index));
            }

            var dto = await _classroomManager.GetByIdAsync<UpdateClassroomDTO>(entityId);

            if (dto != null)
            {
                var checkStudents = await _studentManager.AnyAsync(x => x.Status != Status.Passive && x.ClassroomId == entityId);
                if (checkStudents)
                {
                    TempData["Error"] = "Bu sınıfa kayıtlı öğrenciler vardır. Silinemez!";
                    return RedirectToAction(nameof(Index));
                }

                var result = await _classroomManager.DeleteAsync(dto);
                if (result)
                {
                    TempData["Success"] = "Sınıf silinmiştir!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Sınıf silinememiştir!";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "Sınıf bulunamamıştır!";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "teacher")]
        public async Task<IActionResult> GetClassroomsForTeacherByTeacherId()
        {
            var userDTO = await _userManager.FindUserAsync<GetUserDTO>(HttpContext.User);
            var teacher = await _teacherManager.GetByDefaultAsync<GetTeacherForSelectListDTO>(x => x.Email == userDTO.Email);
            var classrooms = await _classroomManager.GetFilteredListAsync
                (
                    select: x => new GetClassroomVM
                    {
                        Id = x.Id,
                        Name = x.Name,
                        CourseName = x.Teacher.Course.Name,
                        Description = x.Description,
                        TeacherName = x.Teacher.FirstName + " " + x.Teacher.LastName,
                        ClassroomSize = x.Students.Where(x => x.Status != Status.Passive).ToList().Count,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate != null ? x.UpdatedDate.Value.ToString("d.M.yyyy HH:mm:ss") : " - ",
                        Status = x.Status == Status.Active ? "Aktif" : "Güncellenmiş"
                    },
                    where: x => x.Status != Status.Passive && x.TeacherId == teacher.Id,
                    orderBy: x => x.OrderByDescending(z => z.CreatedDate),
                    join: x => x.Include(z => z.Teacher).ThenInclude(z => z.Course).Include(z => z.Students)
                );
            return View(classrooms);
        }

        [Authorize(Roles = "teacher")]
        public async Task<IActionResult> GetStudentsByClassroomId(string classroomId)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(classroomId, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Sınıf bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var students = await _studentManager.GetFilteredListAsync
               (
                  select: x => new StudentDetailForProjectVM
                  {
                      Id = x.Id,
                      FirstName = x.FirstName,
                      LastName = x.LastName,
                      BirthDate = x.BirthDate,
                      Email = x.Email,
                      Exam1 = x.Exam1,
                      Exam2 = x.Exam2,
                      ProjectExam = x.ProjectExam,
                      Average = x.Average,
                      StudentStatus = x.StudentStatus,
                      CourseName = x.Classroom.Teacher.Course.Name,
                      ClassroomName = x.Classroom.Name,

WEB/Areas/Education/Views/Students/CreateStudent.cshtml
@{
    ViewData["Title"] = "Create Student";
}
@model CreateStudentVM

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Yeni Öğrenci Ekle</h3>
            </div>
            <form asp-action="CreateStudent" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="mx-2">
                            <label asp-for="Image"></label>
                            <input id="uploadStudentImage" asp-for="Image" class="form-control" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                        <div>
                            <img id="imageStudent" width="200" height="150" class="rounded-circle justify-content-center" src="~/img/noimage.png" />
                        </div>
                    </div>
                    <div>
                        <label asp-for="FirstName" class="form-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="LastName" class="form-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="BirthDate" class="form-label"></label>
                        <input type="date" asp-for="BirthDate" class="form-control" />
                        <span asp-validation-for="BirthDate" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="Email" class="form-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="RegisterPrice" class="form-label"></label>
                        <input asp-for="RegisterPrice" class="form-control" />
                        <span asp-validation-for="RegisterPrice" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="CourseId" class="form-label"></label>
                        <select onchange="loadTeachersByCourseId(this.value,'teacher-select-student', 'classroom-select-student')" id="course-select" asp-for="CourseId" asp-items="Model.Courses" class="form-control">
                            <option disabled selected value="0">Lütfen kurs seçiniz!</option>
                        </select>
                        <span asp-validation-for="CourseId" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="TeacherId" class="form-label"></label>
                        <select onchange="loadClassroomsByTeacherId(this.value, 'classroom-select-student')" id="teacher-select-student" asp-for="TeacherId" class="form-control">
                        </select>
                        <span asp-validation-for="TeacherId" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="ClassroomId" class="form-label"></label>
                        <select id="classroom-select-student" asp-for="ClassroomId" class="form-control">
                        </select>
                        <span asp-validation-for="ClassroomId" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between" style="height:50px;">
                    <a class="btn btn-outline-dark" asp-action="Index">Geri Dön</a>
                    <button type="submit" class="btn btn-outline-success">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

WEB/Areas/Education/Views/Students/StudentDetail.cshtml
@{
    ViewData["Title"] = "Student Detail";
}
@model StudentDetailForProjectVM

<div class="container rounded bg-white mt-5 mb-5 text-dark">
    <div class="row">
        <div class="col-md-6 border-right">
            @if (User.IsInRole("teacher"))
            {
                <span class="mt-5 text-center">
                    <a asp-controller="Classrooms" asp-action="GetStudentsByClassroomId" asp-route-classroomId="@Model.ClassroomId" class="btn btn-primary profile-button"><i class="fa-solid fa-circle-arrow-left"></i> Geri Dön</a>
                </span>
            }
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                @if (Model.ImagePath != null)
                {
                    <img class="rounded-circle mt-5" width="150" src="~/img/@Model.ImagePath">
                }
                else
                {
                    <img class="rounded-circle mt-5" width="150" src="~/img/noimage.png">

                }
                <span class="font-weight-bold">@Model.FirstName @Model.LastName</span>
                <span class="text-black-50">@Model.Email</span>
            </div>
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Öğrenci Bilgileri</h4>
                </div>
                <div class="row mt-2">
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">Doğum Tarihi</label><h5 class="form-control">
                            @Model.BirthDate.ToShortDateString()
                        </h5>
                    </div>
                    <div class="col-md-12"><label class="labels">Kurs</label><h5 class="form-control">@Model.CourseName</h5></div>
                    <div class="col-md-12"><label class="labels">Sınıf</label><h5 class="form-control">@Model.ClassroomName</h5></div>

                </div>


            </div>
        </div>
        <div class="col-md-6">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Sınavlar</h4>
                </div>
                <form asp-action="UpdateStudentExams">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="FirstName" />
                    <input type="hidden" asp-for="LastName" />
                    <input type="hidden" asp-for="BirthDate" />
                    <input type="hidden" asp-for="Email" />
                    <input type="hidden" asp-for="ClassroomName" />
                    <input type="hidden" asp-for="CourseName" />
                    <input type="hidden" asp-for="ClassroomId" />
                    <input type="hidden" asp-for="Average" />
                    <input type="hidden" asp-for="StudentStatus" />
                    <input type="hidden" asp-for="ProjectName" />
                    <input type="hidden" asp-for="ProjectPath" />
                    <input type="hidden" asp-for="ImagePath" />
                    <div class="col-md-12">
                        <label class="labels">Vize</label>
                        @if (User.IsInRole("teacher"))
                        {
                            <input type="number" min="0" max="100" asp-for="Exam1" class="form-control" />
                        }
                        else
                        {
                            <input type="number" min="0" max="100" asp-for="Exam1" class="form-control" readonly />

                        }
                    </div> <br>
                    <div class="col-md-12">
                        <label class="labels">Final</label>
                        @if (User.IsInRole("teacher"))
                        {
                            <input type="number" min="0" max="100" asp-for="Exam2" class="form-control" />
                        }
                        else
                        {
                            <input type="number" min="0" max="100" asp-for="Exam2" class="form-control" readonly />

                        }
                    </div> <br>
                    <div class="col-md-12">
                        <label class="labels">Proje Notu</label>
                        @if (User.IsInRole("teacher") && Model.ProjectPath != null)
                        {
                            <input type="number" min="0" max="100" asp-for="ProjectExam" class="form-control" />
                        }
                        else
                        {
                            <input type="number" min="0" max="100" asp-for="ProjectExam" class="form-control" readonly />

                        }
                    </div> <br>
                    @if (User.IsInRole("teacher"))
                    {
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-success">Gönder</button>
                        </div>
                    }
                </form>

                <div class="col-md-12">
                    @if (Model.ProjectPath != null)
                    {
                        <label class="labels">Proje</label>
                        <div class="d-flex align-items-start justify-content-between">
                            <h5 class="form-control">@Model.ProjectName - (<span class="text-success">Teslim Edildi</span>)</h5>
                            <a class="btn btn-outline-success ms-2" asp-action="Download" asp-route-filepath="@Model.ProjectPath">
                                <i class="fa-solid fa-download"></i>
                            </a>
                        </div>
                    }
                    else if (User.IsInRole("student"))
                    {
                        <form asp-action="SendProject" enctype="multipart/form-data">
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="FirstName" />
                            <input type="hidden" asp-for="LastName" />
                            <input type="hidden" asp-for="BirthDate" />
                            <input type="hidden" asp-for="Email" />
                            <input type="hidden" asp-for="ClassroomName" />
                            <input type="hidden" asp-for="CourseName" />
                            <input type="hidden" asp-for="ClassroomId" />
                            <input type="hidden" asp-for="Average" />
                            <input type="hidden" asp-for="StudentStatus" />
                            <input type="hidden" asp-for="ImagePath" />
                            <input type="hidden" asp-for="Exam1" />
                            <input type="hidden" asp-for="Exam2" />
                            <input type="hidden" asp-for="ProjectExam" />
                            <input asp-for="ProjectName" class="form-control mb-2" placeholder="Proje adı giriniz..." />
                            <div class="d-flex">
                                <input type="file" class="form-control me-2" asp-for="Project" />
                                <button type="submit" class="btn btn-outline-success">Gönder</button>
                            </div>
                        </form>
                    }
                </div> <br>
                <div class="col-md-12">
                    <label class="labels">Ortalama</label>
                    @if (Model.Average is not null)
                    {
                        <input readonly class="form-control" value="@Model.Average" />
                    }
                    else
                    {
                        <input readonly class="form-control" value="-" />
                    }<br>

                </div>
                <div class="col-md-12">
                    <label class="labels">Durum</label>
                    @if (Model.StudentStatus == ApplicationCore.Consts.StudentStatus.Success)
                    {
                        <h3 class="form-control text-success">Geçti</h3>
                    }
                    else if (Model.StudentStatus == ApplicationCore.Consts.StudentStatus.Failed)
                    {
                        <h3 class="form-control text-danger">Kaldı</h3>
                    }
                    else
                    {
                        <h3 class="form-control text-dark">Devam ediyor...</h3>

                    }
                </div> <br>
            </div>
        </div>
    </div>
</div>