WEB/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB/Areas/Admin/Controllers/RolesController.cs
using AutoMapper;
using Business.Manager.Interface;
using DTO.Concrete.RoleDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WEB.Areas.Admin.Models.ViewModels.Roles;
using WEB.Areas.Admin.Models.ViewModels.Users;

namespace WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private readonly IRoleManager _roleManager;
        private readonly IMapper _mapper;
        private readonly IUserManager _userManager;

        public RolesController(IRoleManager roleManager, IMapper mapper, IUserManager userManager)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var dto = await _roleManager.GetRolesAsync();
            var model = _mapper.Map<List<GetRoleVM>>(dto);
            return View(model);
        }

        public IActionResult CreateRole() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRole(CreateRoleVM model)
        {
            if (ModelState.IsValid)
            {
                if (await _roleManager.CheckRoleNameAsync(model.Name))
                {
                    TempData["Error"] = "Bu rol adı kullanılmaktadır!";
                    return View(model);
                }
                var dto = _mapper.Map<CreateRoleDTO>(model);
                var result = await _roleManager.CreateRoleAsync(dto);
                if (result.Succeeded)
                {
                    TempData["Success"] = "Rol sisteme kaydedilmiştir!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Rol sisteme kaydedilememiştir!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> UpdateRole(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);

            if (!guidResult)
            {
                TempData["Error"] = "Rol bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var dto = await _roleManager.FindRoleByIdAsync<UpdateRoleDTO>(entityId);
            var model = _mapper.Map<UpdateRoleVM>(dto);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRole(UpdateRoleVM model)
        {
            if (ModelState.IsValid)
            {
                if (await _roleManager.CheckRoleNameAsync(model.Name, model.Id))
                {
                    TempData["Error"] = "Bu isim kullanılmaktadır!";
                    return View(model);
                }

                var checkId = await _roleManager.AnyRoleById(model.Id);
                if (!checkId)
                {
                    TempData["Error"] = "Rol bulunamadı!";
                    return RedirectToAction(nameof(Index));
                }

                var dto = _mapper.Map<UpdateRoleDTO>(model);

                var result = await _roleManager.UpdateRoleAsync(dto);
                if (result.Succeeded)
                {
                    TempData["Success"] = "Rol güncellendi!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Rol güncellenemedi!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);

            if (!guidResult)
            {
                TempData["Error"] = "Rol bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var checkId = await _roleManager.AnyRoleById(entityId);
            if (!checkId)
            {
                TempData["Error"] = "Rol bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var checkUser = await _roleManager.CheckAnyUserInRoleAsync(entityId);

            if (checkUser)
            {
                TempData["Error"] = "Bu rolde kullanıcılar vardır. Silinemez!";
                return RedirectToAction(nameof(Index));
            }

            var result = await _roleManager.DeleteRoleAsync(entityId);
            if (result.Succeeded)
            {
                TempData["Success"] = "Rol silinmiştir!";
                return RedirectToAction(nameof(Index));
            }

            TempData["Error"] = "Rol silinememiştir!";
            return Redirect(nameof(Index));
        }

        public async Task<IActionResult> AssignToRole(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);

            if (!guidResult)
            {
                TempData["Error"] = "Rol bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var checkId = await _roleManager.AnyRoleById(entityId);
            if (!checkId)
            {
                TempData["Error"] = "Rol bulunamadı!";
                return RedirectToAction(nameof(Index));
            }
            var dto = await _roleManager.FindRoleByIdAsync<GetRoleDTO>(entityId);
            var vm = _mapper.Map<GetRoleVM>(dto);
            var model = new AssignRoleVM
            {
                Role = vm,
                RoleName = vm.Name,
                HasRole = _mapper.Map<List<GetUserForRoleVM>>(await _userManager.GetUsersHasRoleAsync(vm.Name)),
                HasNotRole = _mapper.Map<List<GetUserForRoleVM>>(await _userManager.GetUsersHasNotRoleAsync(vm.Name))
            };

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignToRole(AssignRoleVM model)
        {
            model.HasRole = _mapper.Map<List<GetUserForRoleVM>>(await _userManager.GetUsersHasRoleAsync(model.RoleName));
            model.HasNotRole = _mapper.Map<List<GetUserForRoleVM>>(await _userManager.GetUsersHasNotRoleAsync(model.RoleName));

            bool resultAdd = true, resultRemove = true;

            foreach (var userId in model.AddIds ?? new string[] {}) 
            {
                resultAdd = await _userManager.AddUserToRoleAsync(Guid.Parse(userId), model.RoleName);
            }

            foreach (var userId in model.RemoveIds ?? new string[] { })
            {
                resultRemove = await _userManager.RemoveUserFromRoleAsync(Guid.Parse(userId), model.RoleName);
            }

            if (resultAdd && resultRemove)
            {
                TempData["Success"] = "İşlem başarılı!";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "İşlem başarısız";
            return View(model);
        }
    }
}

WEB/Areas/Education/Controllers/CoursesController.cs
using ApplicationCore.Consts;
using AutoMapper;
using Business.Manager.Interface;
using DTO.Concrete.CourseDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WEB.Areas.Education.Models.ViewModels.Courses;

namespace WEB.Areas.Education.Controllers
{
    [Area("Education")]
    public class CoursesController : Controller
    {
        private readonly ICourseManager _courseManager;
        private readonly IMapper _mapper;

        public CoursesController(ICourseManager courseManager, IMapper mapper)
        {
            _courseManager = courseManager;
            _mapper = mapper;
        }

        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> Index()
        {
            var courses = await _courseManager.GetFilteredListAsync
                (
                    select: x => new GetCourseVM
                    {
                        Id = x.Id, 
                        Name = x.Name,
                        TotalHour = x.TotalHour != null ? x.TotalHour.ToString() : " - ",
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate != null ? x.UpdatedDate.Value.ToString("d.M.yyyy HH:mm:ss") : " - ",
                        Status = x.Status == Status.Active ? "Aktif" : "Güncellenmiş"
                    },
                    where: x => x.Status != Status.Passive,
                    orderBy: x => x.OrderByDescending(z => z.CreatedDate)
                );

            return View(courses);
        }

        [Authorize(Roles = "admin, customerManager")]
        public IActionResult CreateCourse() => View();

        [Authorize(Roles = "admin, customerManager")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCourse(CreateCourseVM model)
        {
            if (ModelState.IsValid)
            {
                var checkName = await _courseManager.AnyAsync(x => x.Name.ToLower() == model.Name.ToLower());
                if (checkName) 
                {
                    TempData["Error"] = "Bu isimde kurs bulunmaktadır!";
                    return View(model);
                }

                var dto = _mapper.Map<CreateCourseDTO>(model);
                var result = await _courseManager.AddAsync(dto);
                if (result)
                {
                    TempData["Success"] = $"{dto.Name} kursu sisteme kaydedilmiştir!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Bu kurs sisteme kayıt edilememiştir!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> UpdateCourse(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Kurs bulunamadı!";
                return RedirectToAction(nameof(Index));
            }
            var dto = await _courseManager.GetByIdAsync<UpdateCourseDTO>(entityId);
            if (dto != null)
            {
                var model = _mapper.Map<UpdateCourseVM>(dto);
                return View(model);
            }
            TempData["Error"] = "Kurs bulunamadı!";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin, customerManager")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCourse(UpdateCourseVM model)
        {
            if (ModelState.IsValid) 
            {
                var checkName = await _courseManager.AnyAsync(x => x.Name == model.Name && x.Id != model.Id);
                if (checkName)
                {
                    TempData["Error"] = "Bu isim kullanılmaktadı!";
                    return View(model);
                }
                var dto = _mapper.Map<UpdateCourseDTO>(model);
                if (dto != null) 
                {
                    var result = await _courseManager.UpdateAsync(dto);
                    if (result)
                    {
                        TempData["Success"] = "Kurs güncellendi!";
                        return RedirectToAction(nameof(Index));
                    }
                    TempData["Error"] = "Kurs güncellenemedi!";
                    return View(model);
                }
                TempData["Error"] = "Kurs bulunamadı!";
                return View(model);
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        [Authorize(Roles = "admin, customerManager")]
        public async Task<IActionResult> DeleteCourse(string id)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(id, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Kurs bulunamadı!";
                return RedirectToAction(nameof(Index));
            }

            var dto = await _courseManager.GetByIdAsync<UpdateCourseDTO>(entityId);
            if (dto != null)
            {
                var result = await _courseManager.DeleteAsync(dto);
                if (result)
                {
                    TempData["Success"] = "Kurs silindi!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Error"] = "Kurs silinemedi!";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "Kurs bulunamadı!";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("Education/Courses/GetCourseDuration/{courseId}")]
        public async Task<IActionResult> GetCourseDuration(string courseId)
        {
            Guid entityId;
            var guidResult = Guid.TryParse(courseId, out entityId);
            if (!guidResult)
            {
                TempData["Error"] = "Kurs bulunamamıştır!";
                return BadRequest();
            }

            var dto = await _courseManager.GetByIdAsync<GetCourseDTO>(entityId);

            if (dto != null)
            {
                double courseHour = dto != null ? Convert.ToDouble(dto.TotalHour) : 0;
                double courseDay = courseHour / 5;
                double courseWeek = courseDay / 5;
                double daysOfflineCourse = courseWeek * 2;
                double totalDay = courseDay + daysOfflineCourse;
                return Ok(totalDay);
            }
            return NotFound();
        }

        [HttpGet("Education/Courses/GetAllCourses")]
        public async Task<IActionResult> GetAllCourses()
        {
            var courses = await _courseManager.GetCoursesForEarnings();
            if (courses == null)
                return NotFound();

            return Ok(courses);
        }
    }
}

WEB/Views/Shared/_AuthenticationPartial.cshtml
<div class="ms-auto d-flex">
    @if (User.Identity.IsAuthenticated)
    {
        @if (User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a class="btn btn-outline-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin Paneli</a>
            </li>
        }
        <li class="nav-item">
            <a class="btn btn-outline-primary" asp-controller="Account" asp-action="EditUser">Bilgileri Düzenle</a>
        </li>
        <li class="nav-item mx-2">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Çıkış Yap
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Çıkış Yapma Uyarısı</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Çıkış yapmak istediğinize emin misiniz?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Evet</a>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    }
    else
    {
        <li class="nav-item mx-2">
            <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">Giriş Yap</a>
        </li>
    }
</div>

WEB/Views/Shared/_LayoutAdmin.cshtml
@using Business.Manager.Interface
@inject IStudentManager StudentManager;
@{
    var studentImageURL = await StudentManager.GetUserImageURL(User);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB.styles.css" asp-append-version="true" />
    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="~/js/site.js"></script>
</head>
<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                @if (User.IsInRole("admin"))
                {
                    <div class="sidebar-brand-text mx-3">Admin Paneli</div>
                }
                else
                {
                    <div class="sidebar-brand-text mx-3">Eğitim Paneli</div>

                }
            </a>
            <hr class="sidebar-divider my-0">
            @if (User.IsInRole("admin"))
            {

                <li class="nav-item active">
                    <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Admin" asp-controller="Roles" asp-action="Index">
                        <i class="fa-solid fa-gear"></i>
                        <span>Roller</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Admin" asp-controller="CustomerManagers" asp-action="Index">
                        <i class="fa-solid fa-tty"></i>
                        <span>Müşteri Yöneticileri</span>
                    </a>
                </li>
            }
            @if (User.IsInRole("customerManager") || User.IsInRole("admin"))
            {
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Teachers" asp-action="Index">
                        <i class="fa-solid fa-person-chalkboard"></i>
                        <span>Eğitmenler</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Courses" asp-action="Index">
                        <i class="fa-solid fa-school"></i>
                        <span>Kurslar</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Students" asp-action="Index">
                        <i class="fa-solid fa-user-graduate"></i>
                        <span>Öğrenciler</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Classrooms" asp-action="Index">
                        <i class="fa-solid fa-door-open"></i>
                        <span>Sınıflar</span>
                    </a>
                </li>
            }
            @if (User.IsInRole("teacher"))
            {
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Classrooms" asp-action="GetClassroomsForTeacherByTeacherId">
                        <i class="fa-solid fa-door-open"></i>
                        <span>Sınıflarım</span>
                    </a>
                </li>
            }
            @if (User.IsInRole("student"))
            {
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Education" asp-controller="Students" asp-action="StudentDetail">
                        <i class="fa-solid fa-door-open"></i>
                        <span>Notlarım</span>
                    </a>
                </li>
            }
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    @if (ViewContext.HttpContext.Request.Path.ToString().Contains("/Admin/Dashboard"))
                    {
                        <ul class="navbar-nav admin-header">Admin Paneline Hoşgeldiniz!</ul>
                    }
                    else
                    {
                        <ul class="navbar-nav admin-header">Eğitim İşlemleri</ul>
                    }
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity?.Name</span>
                                @if (User.IsInRole("admin"))
                                {
                                    <img class="img-profile rounded-circle"
                                         src="~/img/admin.webp">
                                }
                                else if (User.IsInRole("student"))
                                {

                                    <img class="img-profile rounded-circle"
                                         src="~/img/@studentImageURL">
                                }
                                else if (User.IsInRole("teacher"))
                                {
                                    <img class="img-profile rounded-circle"
                                         src="~/img/teacher.webp">
                                }
                                else if (User.IsInRole("customerManager"))
                                {
                                    <img class="img-profile rounded-circle"
                                         src="~/img/customerManager.jpg">
                                }
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Anasayfaya Dön
                                </a>
                                <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="EditUser">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Bilgileri Düzenle
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Çıkış Yap
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <div class="container-fluid">
                    @if (TempData["Success"] is not null)
                    {
                        <div class="alert alert-success notification">@TempData["Success"]</div>
                    }
                    else if (TempData["Error"] is not null)
                    {
                        <div class="alert alert-danger notification">@TempData["Error"]</div>
                    }
                    @RenderBody()

                </div>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>BilgeAdam - 2024</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Çıkış Yapma Uyarısı!</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Çıkış yapmak istediğinize emin misiniz?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">İptal</button>
                    <a asp-area="" asp-controller="Account" asp-action="Logout" class="btn btn-danger">Evet</a>
                </div>
            </div>
        </div>
    </div>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/js/sb-admin-2.min.js"></script>
    <script src="~/vendor/chart.js/Chart.min.js"></script>
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>